### ISSUE TITLE
Single or double tap on the back button from the homescreen should quit the application

### ISSUE THREAD

**Issue by Porkepix** [coleblvck/AntiiQ#4]
When tapping once or even better twice (to avoid accidental quits) on the back button when on the homescreen, it should qui the application.

**Comment by coleblvck** [comment]
This is one of the improvements I'll be adding in the next update.

It was intentional at first because backing out of the app killed the audio server when there was audio still playing, which was unwanted behaviour but this issue has been fixed ever since. This was also the reason for the additional quit button at the top of the dashboard but I've found that it's not very intuitive so I think double tap would do just fine.

**Comment by coleblvck** [comment]
I have uploaded a release with a dialog when the back button is tapped on the dashboard, with which you can confirm if you'd like to exit the app or not.

**Comment by coleblvck** [comment]
@Porkepix It's quite the convenient feature to have. You should look at the latest update (1.3.2).

**Comment by coleblvck** [comment]
@Porkepix Check [this repo](https://github.com/coleblvck/AntiiQ/releases/tag/1.3.2).

**Comment by coleblvck** [comment]
@Porkepix I personally don't prefer any particular method of exit. The dialog is just something I already put on the table and it doesn't bother me to leave it there as an option. It is also hypothetically useful in any scenario where you do not want to accidentally kill your music app (say water is involved for example).

I've made some changes recently in other to have a more consistent UI across the app and have some more changes in the pipeline, but then, I don't know what specifically you mean and it may not look how I had intended it to on your own device, so you could provide screenshots to help with the consistency across other resolutions and screen sizes.

I have not encountered any glitch like this, and since it's not yet reproducible, I can't narrow it down. We'll see if anyone comes up with a similar issue.

**Comment by coleblvck** [comment]
While the settings were intentionally made to be big, the entire UI seems to appear quite larger on your display. One thing to note though is that the app would still respect your phone settings. So if in your device settings, you have increased your font size or display size, it would reflect on the app too. I have just tested it and that seems to be the case... It seems to do fine under these conditions though from what I can find, but still I'll make some adjustments, like on the equalizer and theme settings pages, nothing is supposed to get cropped out of the screen if the zoom isn't anything out of the ordinary.

**Comment by coleblvck** [comment]
I have uploaded a release in which the scaling of the UI is a bit more dynamic. Some elements might get bigger, some smaller but it'll generally be consistent. For the Equalizer page, I do not know when I'll have the time to get into that but I have noted it.

**Comment by coleblvck** [comment]
I think that page is the settings page and the page is very much scroll-able till every thing is visible.
Even then, I scaled down that page a bit in one of the more recent builds.

**Comment by coleblvck** [comment]
Yes it is actually, a shadow of the mini player.

**Credits to the author of that, though I chose to enable it.
